# $(warning TODO: $(DO_TARGET_MODULE_NAME))
# $(info ALL_DEPENDENCY_DIRS: $(ALL_DEPENDENCY_DIRS))
# $(info ALL_SHARED_LIBRARIES: $(ALL_SHARED_LIBRARIES))
# $(info WANTED_INSTALLED_MODULES: $(WANTED_INSTALLED_MODULES))
# $(info SHARED_LIBRARIES: $(SHARED_LIBRARIES))
# $(info STATIC_LIBRARIES: $(STATIC_LIBRARIES))

.PHONY: all

all: $(DO_TARGET_MODULE_NAME)
